/*
 * cameraDisplayPane.java
 *
 * Created on May 2, 2004, 7:01 PM
 */

/**
 *
 * @author  akrherz
 */
public class cameraDisplayPane extends javax.swing.JPanel {
    
    private String siteID;
    private String sourceID;
    private boolean showWx;
    private String[] wxFields = new String[] {"Air Temps", "Wind Dir/Speed", "Rainfall"};
    private boolean showRadar;
    private schoolNetOb sob;
    private java.awt.Font fatFont;
    private boolean refresherRunning = false;
    
    /** Creates new form cameraDisplayPane */
    public cameraDisplayPane(String myID, String mySource, java.awt.Font myFont) {
        this.siteID = myID;
        this.sourceID = mySource;
        this.fatFont = myFont;
        initComponents();
        initMyComponents();
        
    }
    
    private void runRefresher() {
        if (!this.refresherRunning) {
            
            this.refresherRunning = true;
            
            Thread worker = new Thread() {
                public void run() {
                    while( true  ){
                        java.util.Date now = new java.util.Date();
                        final long ticks = now.getTime();
                        // Only update if it is set to :)
                        if (checkRefreshCamera.isSelected()) {
                            try {
                                
                                cameraScreen.setIcon(new javax.swing.ImageIcon(new java.net.URL( sourceID +"?"+ ticks ) ) );
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        }
                        try{ Thread.sleep(300000); } catch(Exception ex){}
                    }
                }
            };
            worker.start();
        }}
    
    
    
    public void initMyComponents(){
        try {
            this.logoScreen.setIcon(new
                    javax.swing.ImageIcon(getClass().getResource("/images/"+ this.siteID +"_cam.png")));
        } catch (Exception ex) { }
        this.wxPane.setVisible(false);
        this.wxFieldBox2.setSelectedIndex(1);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        logoScreen = new javax.swing.JLabel();
        wxPane = new javax.swing.JPanel();
        wx2 = new JALabel();
        wx1 = new JALabel();
        overlayScreen = new javax.swing.JLabel();
        cameraScreen = new javax.swing.JLabel();
        checkRefreshCamera = new javax.swing.JCheckBox();
        checkHideInLoop = new javax.swing.JCheckBox();
        checkShowWx = new javax.swing.JCheckBox();
        wxFieldBox1 = new javax.swing.JComboBox();
        wxFieldBox2 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setMaximumSize(new java.awt.Dimension(796, 480));
        setMinimumSize(new java.awt.Dimension(796, 480));
        setPreferredSize(new java.awt.Dimension(796, 480));
        add(logoScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 35, 200, 100));

        wxPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wxPane.setBackground(new java.awt.Color(0,0,0,80));
        wx2.setForeground(new java.awt.Color(250, 250, 250));
        wx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wx2.setDoubleBuffered(true);
        wx2.setFont(fatFont);
        wxPane.add(wx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 150, 35));

        wx1.setBackground(new java.awt.Color(255, 255, 255));
        wx1.setForeground(new java.awt.Color(250, 250, 250));
        wx1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wx1.setDoubleBuffered(true);
        wx1.setFont(fatFont);
        wxPane.add(wx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 35));

        add(wxPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 45, 180, 70));

        add(overlayScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 215, 320, 240));

        cameraScreen.setText("It may take 5 minutes for image to appear.  You must have refresh camera activated");
        add(cameraScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 0, 640, 480));

        checkRefreshCamera.setText("Refresh Camera");
        add(checkRefreshCamera, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        checkHideInLoop.setText("Hide In Loop");
        add(checkHideInLoop, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 30, 150, -1));

        checkShowWx.setText("Show Weather");
        checkShowWx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeWxPane(evt);
            }
        });

        add(checkShowWx, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 55, 150, -1));

        wxFieldBox1.setModel(new javax.swing.DefaultComboBoxModel(wxFields));
        wxFieldBox1.setBorder(new javax.swing.border.TitledBorder("Wx Field 1"));
        wxFieldBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wxFieldBoxAH1(evt);
            }
        });

        add(wxFieldBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 85, 150, 50));

        wxFieldBox2.setModel(new javax.swing.DefaultComboBoxModel(wxFields));
        wxFieldBox2.setBorder(new javax.swing.border.TitledBorder("Wx Field 2"));
        wxFieldBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wxFieldBoxAH2(evt);
            }
        });

        add(wxFieldBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 145, 150, -1));

    }//GEN-END:initComponents
    
    private void wxFieldBoxAH2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wxFieldBoxAH2
        // Add your handling code here:
        this.setWeather();
    }//GEN-LAST:event_wxFieldBoxAH2
    
    private void wxFieldBoxAH1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wxFieldBoxAH1
        // Add your handling code here:
        this.setWeather();
    }//GEN-LAST:event_wxFieldBoxAH1
    
    private void changeWxPane(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeWxPane
        // Add your handling code here:
        this.setWeather();
        this.setWeatherPane(!  this.wxPane.isVisible() );
    }//GEN-LAST:event_changeWxPane
    public void setWeatherPane(boolean b){
        this.wxPane.setVisible( b);
        this.checkShowWx.setSelected( b);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cameraScreen;
    private javax.swing.JCheckBox checkHideInLoop;
    private javax.swing.JCheckBox checkRefreshCamera;
    private javax.swing.JCheckBox checkShowWx;
    private javax.swing.JLabel logoScreen;
    private javax.swing.JLabel overlayScreen;
    private JALabel wx1;
    private JALabel wx2;
    private javax.swing.JComboBox wxFieldBox1;
    private javax.swing.JComboBox wxFieldBox2;
    private javax.swing.JPanel wxPane;
    // End of variables declaration//GEN-END:variables
    
    public boolean hideInLoop() {
        return this.checkHideInLoop.isSelected();
    }
    public void setRefreshing(boolean b) {
        this.checkRefreshCamera.setSelected( b);
        runRefresher();
    }
    public void changeRefreshing(){
        this.checkRefreshCamera.setSelected(! checkRefreshCamera.isSelected() );
    }
    
    public void refreshCameraScreen(){
        this.wx1.setText("Hello");
        this.wx2.setText("Hello2");
    }
    
    public void setSOB(schoolNetOb mysob){
        this.sob = mysob;
        this.setWeather();
    }
    
    public void setWeather(){
        if (this.sob == null) return;
        
        int wxcode1 = this.wxFieldBox1.getSelectedIndex();
        int wxcode2 = this.wxFieldBox2.getSelectedIndex();
        
        switch(wxcode1){
            case 0:
                this.wx1.setText( this.sob.getAirTemperature().viewString() +"°F");
                break;
            case 1:
                java.lang.Integer ws = (this.sob.getWindSpeed()).getInteger();
                if (ws.intValue() > 0){
                    this.wx1.setText( this.sob.getWindDirectionText() +" @ "+    (this.sob.getWindSpeed()).viewWindString() );
                }else{
                    this.wx1.setText("Calm");
                }
                break;
            case 2:
                this.wx1.setText("Rain: "+ this.sob.getTodayRainfall().viewString() );
                break;
        }
        
        switch(wxcode2){
            case 0:
                this.wx2.setText( this.sob.getAirTemperature().viewString() +"°F");
                break;
            case 1:
                java.lang.Integer ws = (this.sob.getWindSpeed()).getInteger();
                if (ws.intValue() > 0){
                    this.wx2.setText( this.sob.getWindDirectionText() +" @ "+    (this.sob.getWindSpeed()).viewWindString() );
                }else{
                    this.wx2.setText("Calm");
                }
                break;
            case 2:
                this.wx2.setText("Rain: "+ this.sob.getTodayRainfall().viewString() );
                break;
        }
    }
}
